import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";

const switzer = localFont({
  src: "../../../public/fonts/Switzer-Variable.ttf",
  weight: "100 900",
  display: "swap",
  variable: "--font-switzer",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${switzer.className}  antialiased`}>{children}</body>
    </html>
  );
}
